language: elixir

elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.4
  - 1.7.4

otp_release:
  - 19.0

matrix:
  include:
    - elixir: 1.8.2
      otp_release: 22.0.7
    - elixir: 1.9.1
      otp_release: 22.0.7

script:
  - mix test
